name: Creating a HuaweiCloud private image using HashiCorp Packer.

on:
 push:
   branches:
   - v0.1
 pull_request: {}

env:
  HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
  HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
  PACKER_VERSION: "1.15.0"

jobs:
  build-artifact:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Packer Init
        run: packer init .

      - name: Packer Build - Branches
        run: ./build.sh